### ISSUE TITLE
Background does not look like the right colour in Foot

### ISSUE THREAD

**Issue by revsuine** [prateektade/rosepine-vim#1]
![20240323_16h31m11s_grim](https://github.com/rose-pine/vim/assets/10424281/a1d1254d-3725-4da9-8922-917d7620afdb)

This is what my vim looks like in Foot. Installed with Pathogen as per the instructions and also integrated with Lightline as per the instructions.

My only plugins are:
* Rosé Pine theme
* Lightline
* commentary

Vim version 9.1.0151-2

**Comment by mvllow** [comment]
Are you using tmux or similar?

**Comment by revsuine** [comment]
No, just running vim from zsh in foot. Have tried out launching vim from its .desktop file from rofi and it appears the same too.

**Comment by revsuine** [comment]
Solved: I just needed to `set termguicolors`. Might be worth adding to the README :) Thanks for making the theme!
