### ISSUE TITLE
rosepine_dawn colors not rendering properly

### ISSUE THREAD

**Issue by himanshubanerji** [prateektade/rosepine-vim#2]
I'm using the default macOs terminal (tried it on iTerm2 as well) and background doesn't render properly

<img width="1556" alt="Screenshot 2024-05-16 at 2 55 11 PM" src="https://github.com/rose-pine/vim/assets/42094721/8f351662-91ee-4948-8c3a-8027b21c7610">

**Comment by mvllow** [comment]
It's expected to not work in macOS terminal.app, but for iTerm2—could be related to tmux? I haven't looked at our vim theme in quite some time so it's possible it's a bug.

**Comment by himanshubanerji** [comment]
> It's expected to not work in macOS terminal.app, but for iTerm2—could be related to tmux? I haven't looked at our vim theme in quite some time so it's possible it's a bug.

Yea so after a lot of fiddling I did find adding `set termguicolors` did the trick whereas earlier I was using `set t_Co=256 ` and `set term=xterm-256color` but none of them worked for iTerm2
So for iTerm2 now it does work, but yea for macOS terminal.app it still doesn't, I found a workaround to get similar results which was to go back to default colorscheme and use the rose-pine color profile for the terminal.app

But I still wanted to ask, is there any way it's possible to make it work in the default  macOs terminal.app ? As far as I can see in the settings of the terminal.app , in the advanced tab there is an option to **Declare terminal as: xterm-256colour**, does it not mean that now the default terminal supports 256 colors ?
Or is it like just not possible to do it ?

**Comment by mvllow** [comment]
We would have to choose colours that fit into the 256 range, e.g. from https://www.ditig.com/publications/256-colors-cheat-sheet

I've thought about doing that before when I used terminal.app but even though I prefer using default apps when possible I've found that Kitty/Ghostty are better for my workflow.

**Comment by himanshubanerji** [comment]
> We would have to choose colours that fit into the 256 range, e.g. from https://www.ditig.com/publications/256-colors-cheat-sheet
> 
> I've thought about doing that before when I used terminal.app but even though I prefer using default apps when possible I've found that Kitty/Ghostty are better for my workflow.

Ohh so that means it's possible to tweak your theme to work with terminal.app, thanks for the info :)
I've never tried making my own colorscheme but I'd definately give this a go
Once again thanks :)
